// This file is generated by Pi.Editor, do not modify it!!!
namespace Pi.Gen
{
    /// <summary>
    ///     Int32常量定义
    /// </summary>
    public static class IntConsts
    {
		public const int One = 1;
		public const int Two = 2;
		public const int Three = 3;

    }
}