// This file is generated by Pi.Editor, do not modify it!!!
namespace Pi.Gen
{
    /// <summary>
    ///     组件Id
    /// </summary>
    public enum EComponentId
    {
        ChatComponent = 1,
        ModifierComponent,

    }
}