// This file is generated by Pi.Editor, do not modify it!!!
namespace Pi.Gen
{
    /// <summary>
    ///     非玩家操作码
    /// </summary>
    public enum ENonPlayerOps
    {
        CreatePlayer = -1,

    }
}