// This file is generated by Pi.Editor, do not modify it!!!
namespace Pi.Gen
{
    /// <summary>
    ///     操作码
    /// </summary>
    public enum EOps
    {
		Echo,
		Broadcast,
		Create,
		Destroy,

    }
}