// This file is generated by Pi.Editor, do not modify it!!!
namespace Pi.Gen
{
    /// <summary>
    ///     玩家操作码
    /// </summary>
    public enum EOps
    {
        Create,
        Destroy,
        Echo,
        Broadcast,

    }
}