// This file is generated by Pi.Editor, do not modify it!!!
namespace Pi.Gen
{
    /// <summary>
    ///     属性Id
    /// </summary>
    public enum EPid
    {
        One,
        Two,
        Three,

    }
}